name: Continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency: 
  group: environment-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false # keep on building even if one target fails
      matrix:
        target: [rpipico]
    runs-on: ubuntu-20.04
    steps:
    - name: install build deps
      run: |
        echo "setup_sh=true" >> $GITHUB_ENV
        case ${{ matrix.target }} in
          rpipico)
          PKGS="cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib"
          echo "sub_target=world" >> $GITHUB_ENV
          ;;
          esac
        sudo apt-get update -q
        sudo apt-get install -y byacc automake ${PKGS}
        sudo update-alternatives --set yacc /usr/bin/byacc
    - name: make
      run: ${{ env.setup_sh }} && cd ~ && ls & cd ~/Fleunix/Fleunix/Kernel/platform-rpipico && make ${{ env.sub_target }} -j
    - name: Archive code coverage result
      uses: actions/upload-artifact@v4
      with:
          name: Pi Out
          path: /home/runner/work/Fleunix/Fleunix/Kernel/platform-rpipico
  
