name: Continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  M68K_CROSS_URL: https://mirrors.edge.kernel.org/pub/tools/crosstool/files/bin/x86_64/11.1.0/x86_64-gcc-11.1.0-nolibc-m68k-linux.tar.gz
  M68K_CROSS_DIR: gcc-11.1.0-nolibc

concurrency: 
  group: environment-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false # keep on building even if one target fails
      matrix:
        target: [rpipico]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install build deps
      run: |
        echo "setup_sh=true" >> $GITHUB_ENV
        echo ${{ secrets.GITHUB_TOKEN }} > /tmp/token
        case ${{ matrix.target }} in
          rpipico)
          PKGS="cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib"
          echo "target=TARGET=${{ matrix.target }}" >> $GITHUB_ENV
          echo "sub_target=kernel" >> $GITHUB_ENV
          ;;
          esac
        sudo apt-get update -q
        sudo apt-get install -y byacc automake ${PKGS}
        sudo update-alternatives --set yacc /usr/bin/byacc
    - name: make
      run: ${{ env.setup_sh }} && make ${{ env.cross_cc }} ${{ env.target }} ${{ env.sub_target }} -j`nproc`
    - name: Upload uf2 File
      run: git config --global user.name "PokeyManatee4" && git config --global user.email "null@gmail.com" && git add Build/*.uf2 && git commit -m "Add Binary Files" && git push -u origin main
